### ISSUE TITLE
Create a Twitter banner

### ISSUE THREAD

**Issue by metaproph3t** [metaDAOproject/meta-dao-ops#1]
Most reputable companies and projects use a Twitter banner that jives with their brand. For examples, see [Binance](https://twitter.com/binance), [Ethereum](https://twitter.com/ethereum), and [Colosseum](https://twitter.com/ColosseumOrg). It would be nice if we had the same.

**Comment by nicovrg** [comment]
maybe this is the kind of tasks a contest can be suited for. later might change it again, once the brand is more ironed out

**Comment by metaproph3t** [comment]
Completed by @mgavillo 

![Image](https://github.com/metaDAOproject/meta-dao-ops/assets/108694867/1e99e6ba-0275-4631-b369-0690d3c8d426)
