### ISSUE TITLE
CRM for FaaS

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/meta-dao-ops#15]
1. A channel, DM, TG WHATEVER for potential candidates
2. A point of contact assigned
3. Some set interval updates
4. Integrating the communications and feedback into weekly sprints or assessments
  - make sure we're addressing concerns or getting stuff together for folks such as: more info, graphics, content, designs, on chain stuff etc.
5. Setup a path for folks to get integrated which could include
  - ideas for first use case (first test out a project with some amount of money)
  - ways to onboard (eg setup DAO, transfer funds, setup proposal process)
  - specific use cases we see for them (based on our understanding of their communities and how they're using governance).
6. Set timeline for integration
  - Integration strategy
  - Plan marketing strategy
7. Launch
8. Feedback
9. Iterate

**Comment by nicovrg** [comment]
update on that for posterity
- we now use telegram groups for candidates interaction
- we have a google spreadsheet for the funnel that we go over weekly
- we are making more resources to help dao get onboarded and scale this process 
- interval updates are function of spreadsheet status
(who has to ping us or them, are we on regular updates or waiting for something on their end to get started)

- https://docs.google.com/spreadsheets/d/1LUyAu8v3F6hE8PhMQ3v6UZF4ELsGOY5gYC-ZM6z4w4U/edit?usp=sharing
- https://docs.google.com/document/d/124OXRxPkgcyRuIyVE4D_DfChb0-WtUILFhUSVHUNb4w/edit
- https://docs.google.com/document/d/11AKDoqLRYv-TNnSe4eDtIEp-oL2m9oG_zhSwuwLu134/edit

**Comment by nicovrg** [comment]
coming back here - we moved to notion & this page has the crm info (why we changed & how the current system works)

https://www.notion.so/CRM-fa8ddddd9305420d833448670b5020a3
