### ISSUE TITLE
Create Compensation Spreadsheet and Documentation

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/meta-dao-ops#23]
Based on the discussion.

- [ ] Retroactive
- [ ] One Offs
- [ ] Cyber-agents
- [ ] Entrepreneurs

A spreadsheet should include formula for calculating and well as estimations for examples.

The document should explain at high level and any specific details we want to highlight for its use.

- [ ] Reach out to Dual Finance
- [x] Reach out to Colosseum

**Comment by R-K-H** [comment]
We want to follow up with Colosseum once we have the spreadsheet and examples.

**Comment by metaproph3t** [comment]
Done
