### ISSUE TITLE
Create a landing page

### ISSUE THREAD

**Issue by metaproph3t** [metaDAOproject/meta-dao-ops#3]
Today, our landing page sucks, frankly.

I'd like to have a simpler landing page that conveys what we're doing and our brand identity. For inspiration, see the [Ethereum](https://ethereum.org/en/), [Dyson Swap](https://dysonswap.xyz/), and [Marinade](https://marinade.finance/) landing pages.

**Comment by metaproph3t** [comment]
@Jac0xb is taking a stab at this

**Comment by nicovrg** [comment]
is jacob still on it or has this been free back to the ticket pool?

**Comment by R-K-H** [comment]
> is jacob still on it or has this been free back to the ticket pool?

He's still on it.
