### ISSUE TITLE
Create Sales Sheet for FaaS

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/meta-dao-ops#31]
This should be one to two pages:
- answering the top 3 questions for what is Futarchy and how it works (you can pull from our FAQ) which should be flexible in that it can be adjusted easily for specific customers.
- a structured paragraph how we've seen others adopt it or ideas we have for their specific use (for example, use a symbolic vote as first proposal to see how it works)
- fee structure and details
- onboarding timeline and examples
- contact information

My key with each piece of content we create is make it sharable.. Such that people see it on a desk, they want to pick it up, or its easy to share and understand quickly.

Contact @R-K-H  to generate an example if he hasn't created one yet.

**Comment by R-K-H** [comment]
Developing a full marketing pitch, use content from the FAQ or generate more content as we think or view it right now. What might we need to solve or make understandable for people to see a page and buy or see our pitch and say yes lets do this I have most everything I need to be able to make that choice.

**Comment by nicovrg** [comment]
the first draft can be found here
https://docs.google.com/spreadsheets/d/1LUyAu8v3F6hE8PhMQ3v6UZF4ELsGOY5gYC-ZM6z4w4U/edit#gid=1693561345

we're now using this one
https://www.notion.so/Funnel-21b6848ee5574844bff46a5e47443f4a

the main reason to move it to notion spreasheet is that columns fields should be text (what's the next step), date (time to act), people (who should act) and the rest of info varies between project so i'll be found in the project notion page directly
