### ISSUE TITLE
Review FAQ for FaaS

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/meta-dao-ops#33]
Fine tooth comb review what we're addressing and the content here https://docs.google.com/document/d/124OXRxPkgcyRuIyVE4D_DfChb0-WtUILFhUSVHUNb4w/edit

Specifically review the content and make sure it's aligned with our selling points.

**Comment by nicovrg** [comment]
to my understanding @BlockchainFixesThis worked on this

i copied his work over notion:
https://www.notion.so/FaaS-FAQ-0d16d2c5e69548f6adba938d4f41b55d?pvs=4

original google docs:
https://docs.google.com/document/d/124OXRxPkgcyRuIyVE4D_DfChb0-WtUILFhUSVHUNb4w/edit

@BlockchainFixesThis do you think this is still up to date or does it needs a refreshment?
asking before we close this
