### ISSUE TITLE
Review Onboarding Process for FaaS

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/meta-dao-ops#37]
https://docs.google.com/spreadsheets/d/1LUyAu8v3F6hE8PhMQ3v6UZF4ELsGOY5gYC-ZM6z4w4U/edit?usp=sharing

Need review and to be more structured from a sheet to a document so we can provide more context for training and understanding the why (cross training in case we're asked anyone should be able to and can answer).

**Comment by nicovrg** [comment]
the current spreadsheet is on notion and can be found here
there are three tables: active, onboarding, prospects
templates exists for onboarding and prospects

https://www.notion.so/Funnel-21b6848ee5574844bff46a5e47443f4a?pvs=4
