### ISSUE TITLE
Develop Twitter Marketing Strategy

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/meta-dao-ops#40]
While this is a component of FaaS it should be more broadly a strategy for MetaDAO, which speaks to the need for someone to own this. We can ideally kick it off with FaaS, but doesn't mean we can't leverage our own knowledge and understanding to put into something which supports a team to undertake.

For example:
- Every morning say GM Futards (morning being EST)
- Every evening say GN Futards (evening being EST)
- Post one thread a week
- Post images / memes every day
- Respond to top governance accounts
- Respond to projects we're trying to convince to take up FaaS
- Retweet X, Y and Z's tweets at all times

These are some high level directional tasks, however there likely are larger content strategies based on relevant content and information (for example what we're currently doing).

**Comment by nicovrg** [comment]
mentioned in another ticket, the twitter strategy has been included in the overall growth strategy defined here
https://www.notion.so/Growth-Strategy-c1fa0fc81d2c4d799da0d89c07313a2a?pvs=4
