### ISSUE TITLE
Develop Content Marketing Strategy

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/meta-dao-ops#41]
It's fine to go longer form, and fine for various parties to create it, but we should be aiming for maybe one piece of long form content a week. This gets the brand out there, ideas working within people, keeps things fresh and makes sure we've got something to talk about. At the above it would mean we'd need 3 more people to commit to a piece. Likely we want to establish a theme for the month or relevant to ideas we're currently working on.

This feeds into the twitter strategy as we can post and establish some cadence.

Also we need to publish or discuss pieces which are brought up within the community. We're not short on talent to produce, just some direction by which to send the attention and part of a cohesive strategy, including the why we're doing what we're doing.

**Comment by nicovrg** [comment]
asking for feedback: https://www.notion.so/Growth-Strategy-c1fa0fc81d2c4d799da0d89c07313a2a?pvs=4
