### ISSUE TITLE
Assess and Report Each DAOs Onboarding Status

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/meta-dao-ops#42]
Currently we have various DAOs and while we've documented, I've rarely seen interaction especially over time. This needs to be fixed and we should engage or re-engage so we have a definitive answer. Again not pushy, but these things can't sit and rot.

Use our sheet, and prepare a summary once this is accomplished to be shared with the outreach / onboarding team.

**Comment by nicovrg** [comment]
10 to 20mn of your time to review templates and update state of ongoing dao and i can take this over on a weekly rolling basis

**Comment by R-K-H** [comment]
Cool, if you could make sure you have a proposed status for each one (having reviewed each conversation thus far) even with the context you do have it helps me understand how you consume and understand information. So just make sure you have a status for each, and we can change the status upon review if necessary.
