### ISSUE TITLE
Catalogue things that need to be done in GitHub

### ISSUE THREAD

**Issue by metaproph3t** [metaDAOproject/meta-dao-ops#87]
We should list everything that needs to get done, both short-term and medium-term, in GitHub. This should include the Q3 roadmap items.

**Comment by R-K-H** [comment]
https://futarchy.metadao.fi/metadao/proposals/7AbivixQZTrgnqpmyxW2j1dd4Jyy15K3T2T7MEgfg8DZ

**Comment by metaproph3t** [comment]
Catalogued the stuff that needs to get done:

![Image](https://github.com/user-attachments/assets/ee85e73b-aa75-4cf0-8a6c-a741bb369b34)
