### ISSUE TITLE
Create founding engineer take home task

### ISSUE THREAD

**Issue by R-K-H** [metaDAOproject/meta-dao-ops#95]
For our interview process we require a take home task to accurately assess the candidate. This would be something in the range of one hour to five hours trending towards the lower end, given their skill level and expertise of what we're targeting.

At the end of the day there are many skills that can be trained, but this in essence should assess for what exists at the core / base starting from.

**Comment by metaproph3t** [comment]
Done: https://docs.google.com/document/d/1QDV8r1Lzd7aw-lBX088GI3qdxdCSvNOM8WVplkFO6z4/edit?usp=sharing
